### ISSUE TITLE
A better type for your example

### ISSUE THREAD

**Issue by michaeljota** [maxburs/blog#1]
Instead of creating typing for the function, you could create a type for the _map_ object. 

```
type EventHandlers<T extends OurEvent = OurEvent, P extends T['kind'] = T['kind']> = {
  [K in P]: Function
}

const eventHandlers: EventHandlers = {
  goblins_are_coming: repelMonsters,
  family_is_coming: stockFridge,
};
```

Still, the object type is not narrowing down, but it does compile with no errors. 

[Example](https://www.typescriptlang.org/play/?ssl=25&ssc=1&pln=16&pc=1#code/JYOwLgpgTgZghgYwgAgOIHsBGAbUBRANwnGQG8BYAKGWQGtQATALmQHIBzLXEAZwH04UCHwToAtqHasA3FRo8xEbNhYgArmMzRZlAL5UqoSLEQoAYnAnYAnoWJgycuoxat4V632D9REkFJ0aEHQwYCRVDS0oHX1KKjBrAAcUAHk1KDsSAF40LnwiEgAfZAsPTLAdA0oGCARsQRRRXgchZOwAWXRm6B4WAAoIArAWDBx8+wBKZCyAPmQCdGAGHRq6huQmngct9ARaMygl9gh+wfsWUuAbcqnZ+cXlqoTk5HKACTgQBmwegB4AFWQEAAHpAvjxkGkMkNppD0uUADTIAAKQNBxAYEP+AG1WPQvqwALqwnF4xhEuY5CjUZDYgDSyFAKMJFzUIAQoS6VFiVE2DjO4A+Xx+UF6ryGQu+PVh1JonDGvAEQhE4kkLFaSk63VFCKc7iunm8Kr87BYOz2ByOEF1ekq1Vq9SEGy6WyBLCh5TtArAkpFPGxEAAdPiGISBhMdEA)

Good pattern btw. Thanks!

**Comment by maxburs** [comment]
Nice catch! This makes it _much_ better, I might actually use this pattern again. I'll update my post with this info.

**Comment by maxburs** [comment]
Actually, I think this allows the handling functions be anything, not enforcing any shape on them.
